spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${CADASTRO_DATASOURCE_URL}
    username: ${CADASTRO_DATASOURCE_USER}
    password: ${CADASTRO_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    exchenge:
      producer: ${RABBITMQ_EXCHENGE}
    routing-key:
      producer: ${RABBITMQ_QUEUE}
    dead-letter:
      producer: ${RABBITMQ_DEADLETTER}

eureka:
  instance:
    hostname: ${EUREKA_SERVER}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${REGISTER_SERVER_URL}

cadastro:
  rabbitmq:
    exchenge: ${RABBITMQ_EXCHENGE}
    routingkey: ${RABBITMQ_QUEUE}
    deadLetter: ${RABBITMQ_DEADLETTER}