spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${CADASTRO_DATASOURCE_URL}
    username: ${CADASTRO_DATASOURCE_USER}
    password: ${CADASTRO_DATASOURCE_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

eureka:
  instance:
    hostname: ${EUREKA_SERVER}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${REGISTER_SERVER_URL}
