spring:
  application:
    name: cadastro
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro
    username: admin
    password: admin

