server:
  port: 8081
  servlet:
    context-path: /cadastro

spring:
  application:
    name: cadastro
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false