spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro
    username: admin
    password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    exchenge:
      producer:  ex.cadastro
    routing-key:
      producer: rk.cadastro
    dead-letter:
      producer: dl.cadastro
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:keys/auth-pubkey.txt

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

cadastro:
  rabbitmq:
    exchenge: ex.cadastro
    routingkey: rk.cadastro
    deadLetter: dl.cadastro