spring:
  application:
    name: cadastro
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  jmx:
    enabled: false
  datasource:
    url: ${CADASTRO_DATASOURCE_URL}
    username: ${CADASTRO_DATASOURCE_USER}
    password: ${CADASTRO_DATASOURCE_PASSWORD}

