server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: cadastro
          uri: lb://CADASTRO
          predicates:
            - Path=/cadastro/**
        - id: venda
          uri: lb://VENDA
          predicates:
            - Path=/venda/**
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
