server:
  port: 8080

spring:
  application:
    name: gateway

zuul:
  prefix: /api
  ignored-services: "*"

  routes:
    crud:
      path: /cadastro/**
      service-id: cadastro
      strip-prefix: false
      custom-sensitive-headers: true

    pagamento:
      path: /venda/**
      service-id: venda
      strip-prefix: false
      custom-sensitive-headers: true