jwt:
  key-store-path: ${KEY_STORE_PATH}
  secret-key: ${KEY_SECRET}
  key-pair-alias: ${KEY_ALIAS}

spring:
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${AUTH_DATASOURCE_USER}
    password: ${AUTH_DATASOURCE_PASSWORD}
