spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: admin
    password: admin

security:
  jwt:
    token:
      secret-key: chave_secreta
      expire-length: 3600
