jwt:
  key-store-path: keys/auth.jks
  secret-key: dW5pdmVyc2FsLWF1dGhvcml6YXRpb24tc2VydmVyLWZpbGUK
  key-pair-alias: authkey

spring:
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: admin
    password: admin
    initialization-mode: always

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
