eureka:
  instance:
    hostname: ${EUREKA_SERVER}
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${SERVER_EUREKA_URL}/eureka