spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/venda
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/register/eureka

